### PR TITLE
Added governance document

### PR DESCRIPTION
**Pull request by robertoostenveld**
This PR includes the governance document on the website. I have added it as main menu item, which is probably suboptimal, but as good as it goes at this moment. 

This relates to https://github.com/bids-standard/bids-specification/pull/354

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Merging the governance to my copy on https://robertoostenveld.github.io/bids-website/governance.html, I see some issues:

- [ ] the heading levels should be improved, now most are one level too deep 
- [ ]  the internal links in the ToC should be fixed
- [ ]  the figure just under heading 3 should be added
- [ ]  the URLs at the bottom should link to the actual websites/pages
- [ ] email addresses should be linked
- [ ] the link to the list of BEPs should be updated

**Comment by KirstieJane** [comment]
I think this addition should be agreed by a broader community than the folks who monitor github - can we add this to the community forum agenda before merging?

**Comment by melanieganz** [comment]
I agree with Kirstie. Maybe we can just ask how people feel about this in the community forum. But I also want to point out that normally you can find such information on websites of organizations (clubs, etc.), so myself I am in favor of having it on the website.

**Comment by robertoostenveld** [comment]
> I think this addition should be agreed by a broader community 

Just for clarification: You mean the addition of the governance document to this specific "bids.neuroimaging.io" website, or the formatting changes (my addition of links?) to the document, or the document itself?

**Comment by robertoostenveld** [comment]
> But I also want to point out that normally you can find such information on websites of organizations

The [acknowledgements](https://robertoostenveld.github.io/bids-website/governance.html#f-acknowledgements) in the BIDS governance document itself link to >10 other projects that have their governance documented on their main website. 

The idea of **not** having the governance on "bids.neuroimaging.io" suggests to me that we might not want that to be the main website.

**Comment by melanieganz** [comment]
Sorry, my comment was referring to having the document on the main webpage and I also was thinking that this is what Kirstie referred to.  I am like you in favor of this. Formatting changes are fine for me.

**Comment by robertoostenveld** [comment]
@melanieganz once more for clarification: with "main webpage" do you mean the website "bids.neuroimaging.io" (i.e. anywhere on that site), or do you mean that "governance" appears in the main/front/home page on that website?

I agree that governance being listed in the top-level menu is not ideal, the structure of the website needs more work and (probably) should become properly hierarchical (including menu + submenus). But whether we should first add content, and have the structure follow, or the other way around, I don't know. Right now I do mostly care about content, less about structure, hence my present contributions.

**Comment by melanieganz** [comment]
@robertoostenveld sorry, i mean the first case, so it should appear anywhere on the website "bids.neuroimaging.io". If as a main point or under some other tab is I think secondary right now, like you also say.

**Comment by robertoostenveld** [comment]
Since I opened this PR, I propose that someone else approves of it and merges it for release on the  website.

**Pull request merged**
