### PR TITLE
[ENH] centralize and standardize BEP process material

### LINKED ISSUE #197: Make the BEP process more obvious on the website
It seems that most of our BEP process is either stored in google docs, or on the wiki of some of the repos. 

https://github.com/bids-standard/bids-specification/wiki

I suspect some of the important but implicit details of the process are also stored in the grey matter of several of the maintainers + steering committee. :smile: 

This kinda makes it hard for outsiders to see and understand how they should go about contributing to BIDS when it comes to BEP.

I suggest we try to centralize most of that information into a single page on the website and add a very obvious link to this on the landing page.

### PR DESCRIPTION
**Pull request by Remi-Gau**
closes #197

- [x] move material out of google doc (BEP Lead Guidelines):
  - https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4
- [x] move material out of BIDS spec wiki (BEP submission process):
  - https://github.com/bids-standard/bids-specification/wiki/BIDS-Extension-Proposal-(BEP)-submission-process

### CODE REVIEW

**Comment by sappelhoff** [comment]
Thanks for all your work on this Remi! Seems like you're on a roll. Could you please add links in your PR description to the original sources that are now being migrated here?

**Comment by Remi-Gau** [comment]
Will do though those links will die once we remove the content from the Google drive.

**Comment by Remi-Gau** [comment]
> Seems like you're on a roll.

More like on a bout of late "spring" cleaning of our internal documentation.

**Review by sappelhoff — APPROVED** [review]
Thanks a lot, this looks good to me. Centralizing these resources is important.

**Review by ericearl — APPROVED** [review]
I think these look great for starters, rock and roll! We can always iterate on necessary improvements, but this will get the words out on the website where they should be hosted.

**Comment by Remi-Gau** [comment]
OK will merge for now and remove / deprecate the source material.

Let's update the material here directly from now on

**Pull request merged**
