### PR TITLE
[ENH] update bids apps listing

### PR DESCRIPTION
**Pull request by Remi-Gau**
add bibsnet and petdeface

### CODE REVIEW

**Comment by Remi-Gau** [comment]
https://bids-website--478.org.readthedocs.build/en/478/tools/bids-apps.html

image

**Review by bendhouseart — APPROVED** [review]
Cool it shows the little code commit badge! 

Does this use the same jinja template as the bids-apps website?

**Comment by Remi-Gau** [comment]
> Does this use the same jinja template as the bids-apps website?

nope: given the old bids app website will be fused into the new bids website, I nuked whatever I was using before

**Comment by bendhouseart** [comment]
> > Does this use the same jinja template as the bids-apps website?
> 
> nope: given the old bids app website will be fused into the new bids website, I nuked whatever I was using before

🙈

**Pull request merged**
