### PR TITLE
Add The Neuro application to the website

### PR DESCRIPTION
**Pull request by franklin-feingold**
PR adds our application to [The Neuro Open Science in action prize 2020](https://www.mcgill.ca/neuro/open-science/neuro-open-science-action-prize-2020) to the website. Currently, I placed the application in this repository for now. I think this can be better placed (perhaps on OSF so it can get a DOI). I think that can be incorporated into the collaboration pillar implementation

### CODE REVIEW

**Review by sappelhoff — COMMENTED** [review]
+1 to place the application on OSF, get a DOI, and integrate the DOI here instead of the pdf file

**Comment by franklin-feingold** [comment]
If I may clarify - I meant to temporarily place the application here in the interest of sharing it. The long term living place will be OSF as the collaboration pillar is implemented. I would prefer to implement prior to placing documents.

**Comment by sappelhoff** [comment]
So in the long run you want to place the application on OSF - but not right now, because you first want to create a new OSF account?

And until then you want to upload it here? It's not ideal, but I guess it's fine - feel free to merge if you want to do it this way :-)

**Comment by robertoostenveld** [comment]
I do see a general challenge in mapping specific work done for BIDS to OSF, since OSF is more tailored to projects (or traditional publications), whereas the BIDS "endeavour" at large with all its collaborators is more process-oriented. I don't think that "new" OSF accounts are going to solve this challenge; I expect that we all have our personal accounts already (as e.g. used here https://osf.io/yn93h/).

In this case, I would consider the "The Neuro" application as a project within this larger BIDS endeavour/process, and therefore I think it should be its own OSF entity/project.

**Comment by franklin-feingold** [comment]
I think my organizational design addresses that. I want to plan out the collaboration scheme prior to placing files around OSF. I am currently scoping out the collaboration pillar so once the implementation starts we'll be able to move this file to its long-term home. Once the full picture has been scoped, it will clarify the implementation.

I agree, I see OSF as housing our completed works rather than the process documents. We can utilize their folder scheme to add an additional layer of organization to the project. Perhaps to clarify - this will likely be primarily applied to the collaboration pillar documents. I agree that the BEP/standard processes are more process-orientated rather than deliverable-orientated (with the deliverable incorporated into the specification, validator, and example repositories). 

Regarding this particular document - I can see it classified along the lines of: `BIDS grant applications`. That will allow us to place all of our applications there. Though, scoping out the full collaboration pillar will reveal the approach.

**Comment by sappelhoff** [comment]
I guess we can merge this, it's only ~350kb and I am fine with this as a short term solution. Thanks Franklin, and thanks Robert for your comments.

**Pull request merged**
