### PR TITLE
[ENH] add BIDS cfood as a tool

### PR DESCRIPTION
**Pull request by Remi-Gau**

### CODE REVIEW

**Comment by Remi-Gau** [comment]
see here: https://neurostars.org/t/plugin-for-bids-search-bids-data-and-combine-more-easily-with-other-data-sets/25560

**Comment by twindiscale** [comment]
Would love to see this live! Thomas

**Comment by twindiscale** [comment]
> 

Great! Is there any other way we can make this more widely known to the community? Would be happy to give an intro if you have a regular community call or something like that.

**Comment by Remi-Gau** [comment]
@twindiscale 
A low hanging fruit would be the bids mailing list: https://groups.google.com/g/bids-discussion
I don't remember seeing it there

**Pull request merged**
