### PR TITLE
add starter-kit redirect to bids-starter-kit

### LINKED ISSUE #171: Redirect to starter kit?
In light of discussion where starter kit might get overhauled, having a redirect might give us flexibility to move it in the future without breaking old versions of the spec.

We could use https://bids.neuroimaging.io/starter-kit

### PR DESCRIPTION
**Pull request by sappelhoff**
closes #171 

@effigies is this what you had in mind?

### CODE REVIEW

**Comment by effigies** [comment]
What would the effect of this be?

**Comment by sappelhoff** [comment]
you'll be able to do https://bids.neuroimaging.io/starter-kit and have it direct you to the bids-starter-kit 

there may be another way to do it, but I piggy backed on the setup we have for BEP redirection

**Comment by sappelhoff** [comment]
see: https://50-164719390-gh.circle-artifacts.com/0/_site/starter-kit.html

**Comment by effigies** [comment]
Got it. LGTM.

**Pull request merged**
