### PR TITLE
Add news post about BIDS Community Survey 2024

### PR DESCRIPTION
**Pull request by ericearl**
It's the announcement of the BIDS community survey 2024 for the BIDS website.

### CODE REVIEW

**Comment by ericearl** [comment]
I just realized I messed something up. Don't merge this yet...

**Comment by ericearl** [comment]
Okay, I think it looks right now.

**Comment by effigies** [comment]
That QR code seems unnecessarily large, IMO. Otherwise this LGTM.

**Comment by sappelhoff** [comment]
> That QR code seems unnecessarily large, IMO. Otherwise this LGTM.

That seems to be easily fixable in Jekyll, see: https://github.com/bids-standard/bids-website/pull/368/commits/f946556868a78b45ebc51ef25c6d248eaa22a5c1

image

**Review by effigies — APPROVED** [review]

**Pull request merged**
