### PR TITLE
Extra SAMRI information

### PR DESCRIPTION
**Pull request by TheChymera**
@sappelhoff 

SAMRI also includes plenty of analysis and preprocessing functions for BIDS archives, and we already have [an article which documents and benchmarks the registration workflow](https://www.sciencedirect.com/science/article/pii/S1053811921006625).
Is there any other place on the website where I could add this?

### CODE REVIEW

**Review by sappelhoff — APPROVED** [review]
thanks!

>  Is there any other place on the website where I could add this?

The article is already linked via the `doc` column:

image

I can't think of a place on the website where you could add more info - I think it's better to be concise here, because we are listing so many tools :-)

**Comment by Remi-Gau** [comment]
@TheChymera maybe on the BIDS starter kit ?

We could start a page under Resources?

**Comment by TheChymera** [comment]
@sappelhoff 
> The article is already linked via the `doc` column:

That is the repositing article, we also have a registration article.

@Remi-Gau 
> We could start a page under Resources?
Apologies, I'm just familiarizing myself with this repository, but where would that be?
`find -name "*esources*"` in the repo directory returns nothing.

**Comment by Remi-Gau** [comment]
> > We could start a page under Resources?
> 
> Apologies, I'm just familiarizing myself with this repository, but where would that be? `find -name "*esources*"` in the repo directory returns nothing.

gosh. my previous reply without a link was quite unhelpful. Sorry about that.

So I meant under "resources" in the TOC in the left hand column of the jupyter book.
https://bids-standard.github.io/bids-starter-kit/

The TOC is configured here: https://github.com/bids-standard/bids-starter-kit/blob/f837e0e28c0c6f42bf523a61b5657771703e1158/src/_toc.yml#L15

**Comment by TheChymera** [comment]
@Remi-Gau but that should be a separate PR for this repository: https://github.com/bids-standard/bids-starter-kit
Right?

**Comment by Remi-Gau** [comment]
> @Remi-Gau but that should be a separate PR for this repository: https://github.com/bids-standard/bids-starter-kit Right?

yup

**Comment by TheChymera** [comment]
@sappelhoff so this should be ok now?

**Comment by sappelhoff** [comment]
> @sappelhoff so this should be ok now?

yup, I was just waiting for the discussion :-) 

Thanks for adding the info!

**Pull request merged**
