### PR TITLE
Blog post: Announcing Community Forum Events

### PR DESCRIPTION
**Pull request by KirstieJane**
This blog post announces the community forum events on 14 and 16 January 2020.

I've "scheduled" it for 2 January 2020 because I figured it makes sense to post when folks are more likely to be back to work?

If anyone is around to review and merge that would be great ✨  (Don't worry if not, I wasn't working over the holidays and so you shouldn't have to either 💖)

Other tasks for steering group members:

- [ ] Approve eventbrite link by adding a :+1: to this PR
- [ ] Approve google form by adding a 🎉 to this PR

### CODE REVIEW

**Comment by robertoostenveld** [comment]
The google form states "... will take place  January 14 ... **or** January 16", which suggests that it is on one of the two dates.
. 
Can you change that into "... **and on** ..."?

**Comment by KirstieJane** [comment]
Changed the google form @robertoostenveld - should look ok now :)

@sappelhoff - the eventbrite is still private so it's ok that it doesn't work for you. @franklin-feingold will be able to add you and review (and maybe make public) when he's at work in a few hours :star2:

**Comment by robertoostenveld** [comment]
I just merged it with my repository to see how it renders. See https://robertoostenveld.github.io/bids-website/news.html

The link to the "BIDS Steering Group" post (after updating the base URL) is https://bids.neuroimaging.io/2019/12/31/meet-the-bids-steering-group.html, which exists but does not include the photo's properly. I will look into this.

**Comment by franklin-feingold** [comment]
@KirstieJane the eventbrite is live!

@sappelhoff added you to our EventBrite group!

**Comment by robertoostenveld** [comment]
@KirstieJane I think this is ready to be merged and put online.

**Pull request merged**
