### PR TITLE
fix incf link

### LINKED ISSUE #50: Broken links
At the bottom of https://bids.neuroimaging.io/ the link to the INCF is incorrect. Also the link on the INCF site for the task force has been moved/removed.

The Feedback link at the top of the page sends you to the bottom of the page but there's nothing there about giving feedback...

### PR DESCRIPTION
**Pull request by sappelhoff**
closes #50 

- ~~Feedback form re-enabled~~ see #52 
- [x] Fix INCF link
- [ ] resolved issue why INCF wiki link to task-force is not responding

For now, I only fixed one of the issues. I don't know which alternative link I should use for the INCF task force link.

And I am waiting for information from @franklin-feingold regarding the feedback form.

### CODE REVIEW

**Comment by franklin-feingold** [comment]
just made [the form](https://forms.gle/pPU6dwhqUvY8SAZ47) - I'll open a PR on your fork to incorporate into this

**Comment by sappelhoff** [comment]
Cool, now we just need to replace this link, which seems to be broken: wiki.incf.org/mediawiki/index.php/Neuroimaging_Task_Force

... :thinking:

**Comment by sappelhoff** [comment]
@rwblair can you review and approve if everything is fine? :-)

**Comment by rwblair** [comment]
@sappelhoff sorry for the delay

**Pull request merged**
